"""
Django settings for farmacia project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd4*_2o27&wi%e@!43^j6k#=wy^_5s@npjhv!x!l$p5_yg3jr!8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'account', # Esta es la aplicación correspondiente al módulo de autenticación y cuentas de usuario 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "bootstrap4", # Este componente permite utilizar Bootstrap en los formularios que se utilicen dentro de la aplicación.
    'bootstrapform', # Este componente permite utilizar Bootstrap en los formularios que se utilicen dentro de la aplicación.    
    'bootstrap_datepicker_plus', # Este componente permite utilizar el componente datepicker para la visualización del calendario para las fechas
    'webfarmacia',
    'cliente',
    'empleado',
    'proveedor',
    'producto',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'farmacia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'farmacia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'farmacia',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_URL = '/static/'

# Configuración para la URL donde será direccionado el usuario luego de hacer Login en la aplicación
LOGIN_REDIRECT_URL = '/webfarmacia/'

# Configuración para la URL donde será direccionado el usuario luego de hacer Logout en la aplicación
# LOGOUT_REDIRECT_URL = '/accounts/login'
LOGOUT_REDIRECT_URL = '/webfarmacia/'

# Configuración para el envío de correos. Recuperación de contraseña
# La plataforma de envío de correos utilizada es Mailtrap y las credenciales de acceso a dcicha plataforma son las siguientes:
# Usuario: fredy.montanaa@cun.edu.co
# Contraseña: FredY2709**
EMAIL_HOST = 'smtp.mailtrap.io'
EMAIL_HOST_USER = '5a3921708c5ef5'
EMAIL_HOST_PASSWORD = 'cf8152207006d4'
EMAIL_PORT = '2525'

# Configuración de la URL relativa para guardar los archivos cargados desde la aplicación
MEDIA_ROOT = os.path.join(BASE_DIR, 'user')
MEDIA_URL = '/user/'

BOOTSTRAP4 = {
    'include_jquery': True,
}