# Generated by Django 3.1.7 on 2021-04-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sexo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='sexo',
            name='nombre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(max_length=24),
        ),
    ]
